"""Generate the registry views from data/sources.yml.

Vaults hold judgment; the registry holds dispatch. This script reads the
single registry file and writes four generated pages under docs/registry/:

    index.md          what the registry is, plus coverage stats
    radar.md          what is coming, and what just concluded
    harvest-queue.md  concluded + open material + no vault yet  <- the actionable one
    by-topic.md       every source grouped by topic, across types
    watchlist.md      journals and news, deliberately kept separate

Usage:
    python3 scripts/build_registry.py [--today YYYY-MM-DD] [--check]

--check exits non-zero if the generated pages would differ from what is on
disk, so CI can catch a stale commit.
"""

from __future__ import annotations

import argparse
import datetime as dt
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
REGISTRY = REPO / "data" / "sources.yml"
OUT_DIR = REPO / "docs" / "registry"

BANNER = (
    "<!-- GENERATED BY scripts/build_registry.py — DO NOT EDIT BY HAND.\n"
    "     Edit data/sources.yml and re-run the script. -->\n\n"
)

EVENT_TYPES = {"conference", "webinar"}
FEED_TYPES = {"journal", "news"}

# How much material each access level actually yields, in plain words.
ACCESS_NOTE = {
    "open": "open",
    "mixed": "partly open",
    "gated": "gated",
    "dead": "offline",
}

RADAR_WINDOW_DAYS = 150
RECENT_WINDOW_DAYS = 120


def load():
    with REGISTRY.open() as fh:
        doc = yaml.safe_load(fh)
    return doc["meta"], doc["sources"]


def as_date(value):
    if value is None:
        return None
    if isinstance(value, dt.date):
        return value
    return dt.date.fromisoformat(str(value))


def date_range(src) -> str:
    start, end = as_date(src.get("start")), as_date(src.get("end"))
    if start is None:
        return "unscheduled"
    if end is None or end == start:
        return start.strftime("%b %-d, %Y")
    if (start.year, start.month) == (end.year, end.month):
        return f"{start.strftime('%b %-d')}–{end.strftime('%-d, %Y')}"
    if start.year == end.year:
        return f"{start.strftime('%b %-d')} – {end.strftime('%b %-d, %Y')}"
    return f"{start.strftime('%b %-d, %Y')} – {end.strftime('%b %-d, %Y')}"


def vault_link(src, depth=1) -> str:
    """Link to the vault, or say plainly that there isn't one."""
    if not src.get("vault"):
        return "—"
    prefix = "../" * depth
    return f"[{src['status']}]({prefix}{src['vault']})"


def harvest_cell(src) -> str:
    h = src.get("harvest") or {}
    method = h.get("method") or "—"
    return f"`{method}`"


def is_event(src) -> bool:
    return src["type"] in EVENT_TYPES


def concluded(src, today) -> bool:
    end = as_date(src.get("end"))
    return end is not None and end < today


def harvestable(src) -> bool:
    """Material we could actually get at without a login."""
    return src.get("access") in {"open", "mixed"} and (src.get("harvest") or {}).get(
        "method"
    ) not in {None, "none"}


def write(path: Path, body: str, check: bool, stale: list):
    text = BANNER + body.rstrip() + "\n"
    if check:
        current = path.read_text() if path.exists() else ""
        if current != text:
            stale.append(path.relative_to(REPO))
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)


# ─────────────────────────────── page builders ───────────────────────────────


def page_index(meta, sources, today) -> str:
    events = [s for s in sources if is_event(s)]
    feeds = [s for s in sources if s["type"] in FEED_TYPES]
    built = [s for s in events if s["status"] == "built"]
    scaffold = [s for s in events if s["status"] == "scaffold"]
    novault = [s for s in events if s["status"] == "none"]
    queue = [
        s for s in events if concluded(s, today) and harvestable(s) and s["status"] != "built"
    ]

    L = [
        "# Source registry",
        "",
        "**One file describes every source this corpus tracks; these pages are generated from it.**",
        "The registry is a dispatch layer — what exists, when it happens, whether the material is",
        "reachable, and how to get it. The vaults themselves hold the judgment about what any of it means.",
        "",
        f"Registry last updated **{meta['updated']}** · views generated for **{today.isoformat()}**.",
        "",
        "## Coverage",
        "",
        "| | Count |",
        "|---|---|",
        f"| Events tracked (conferences + webinar series) | **{len(events)}** |",
        f"| — with a built vault | {len(built)} |",
        f"| — scaffolded, awaiting material | {len(scaffold)} |",
        f"| — no vault yet | {len(novault)} |",
        f"| Journals and news feeds on the watchlist | **{len(feeds)}** |",
        f"| **Concluded, reachable, not yet built** | **{len(queue)}** |",
        "",
        f"That last row is the one that matters. See **[Harvest queue](harvest-queue.md)**.",
        "",
        "## The three views",
        "",
        "**[Radar](radar.md)** — what is coming in the next few months, so a vault gets scaffolded",
        "*before* a meeting rather than reconstructed from archives afterwards. AACR IO 2026 is the",
        "cautionary case: its program pages went offline after the meeting and had to be rebuilt from",
        "Wayback snapshots.",
        "",
        "**[Harvest queue](harvest-queue.md)** — meetings that have already happened, whose material is",
        "open, and which have no built vault. This is the working list. Pick from it rather than asking",
        "what is missing.",
        "",
        "**[By topic](by-topic.md)** — every source under each topic, crossing conferences, webinars,",
        "journals, and news. Use it when the question is subject-shaped rather than calendar-shaped.",
        "",
        "**[Watchlist](watchlist.md)** — journals and news, kept deliberately separate. They are a",
        "firehose; curated vaults and an aggregator feed are different products and mixing them dilutes",
        "both.",
        "",
        "## Editing",
        "",
        "Edit `data/sources.yml`, then regenerate:",
        "",
        "```bash",
        "python3 scripts/build_registry.py",
        "```",
        "",
        "Every page here carries a do-not-edit banner because the script overwrites them. Run with",
        "`--check` to verify the committed pages match the registry — it exits non-zero when they drift.",
        "",
        "## Fields worth knowing",
        "",
        "`access` records how reachable the material is (`open`, `mixed`, `gated`, `dead`), and `harvest`",
        "records the method and endpoint — a Crossref query, a YouTube playlist, a Wayback prefix. Those",
        "two fields are the accumulated cost of every vault built so far, written down instead of",
        "rediscovered. Entries carrying `verify: true` have at least one unconfirmed field.",
    ]
    return "\n".join(L)


def page_radar(sources, today) -> str:
    events = [s for s in sources if is_event(s) and as_date(s.get("start"))]
    upcoming = sorted(
        (s for s in events if as_date(s["start"]) >= today),
        key=lambda s: as_date(s["start"]),
    )
    soon = [
        s for s in upcoming if (as_date(s["start"]) - today).days <= RADAR_WINDOW_DAYS
    ]
    later = [s for s in upcoming if s not in soon]
    recent = sorted(
        (s for s in events if concluded(s, today)
         and (today - as_date(s["end"])).days <= RECENT_WINDOW_DAYS),
        key=lambda s: as_date(s["end"]),
        reverse=True,
    )
    unscheduled = [s for s in sources if is_event(s) and not as_date(s.get("start"))]

    L = [
        "# Radar",
        "",
        f"Generated for **{today.isoformat()}**.",
        "",
        "The point of this page is to scaffold a vault *before* a meeting, not after. Program pages get",
        "retired, virtual platforms close, and speaker lists vanish — AACR IO 2026's entire program is",
        "now 404 on the live site and survives only in Wayback snapshots.",
        "",
        f"## Next {RADAR_WINDOW_DAYS} days",
        "",
    ]
    if soon:
        L += [
            "| In | Event | Dates | Location | Access | Vault |",
            "|---|---|---|---|---|---|",
        ]
        for s in soon:
            days = (as_date(s["start"]) - today).days
            when = "this week" if days <= 7 else f"{days} d"
            L.append(
                f"| {when} | **{s['name']}** | {date_range(s)} | {s.get('location','—')} "
                f"| {ACCESS_NOTE.get(s.get('access'),'—')} | {vault_link(s)} |"
            )
    else:
        L.append("*Nothing scheduled in this window.*")

    L += ["", f"## Recently concluded (last {RECENT_WINDOW_DAYS} days)", ""]
    if recent:
        L += [
            "Material from these is freshest and least likely to have been taken down yet.",
            "",
            "| Event | Ended | Access | Harvest | Vault |",
            "|---|---|---|---|---|",
        ]
        for s in recent:
            L.append(
                f"| **{s['name']}** | {date_range(s)} | {ACCESS_NOTE.get(s.get('access'),'—')} "
                f"| {harvest_cell(s)} | {vault_link(s)} |"
            )
    else:
        L.append("*Nothing concluded in this window.*")

    L += ["", "## Further out", ""]
    if later:
        L += ["| Event | Dates | Location | Vault |", "|---|---|---|---|"]
        for s in later:
            L.append(
                f"| {s['name']} | {date_range(s)} | {s.get('location','—')} | {vault_link(s)} |"
            )
    else:
        L.append("*Nothing further out on the registry.*")

    if unscheduled:
        L += ["", "## Unscheduled", "", "Dates not yet announced:", ""]
        for s in unscheduled:
            L.append(f"- **{s['name']}** — {vault_link(s)}")

    return "\n".join(L)


def page_harvest_queue(sources, today) -> str:
    events = [s for s in sources if is_event(s)]
    queue = [
        s for s in events
        if concluded(s, today) and harvestable(s) and s["status"] != "built"
    ]
    queue.sort(key=lambda s: (s["status"] != "none", -as_date(s["end"]).toordinal()))

    open_only = [s for s in queue if s.get("access") == "open"]
    gated = [
        s for s in events
        if concluded(s, today) and s["status"] != "built" and not harvestable(s)
    ]

    L = [
        "# Harvest queue",
        "",
        f"Generated for **{today.isoformat()}**.",
        "",
        "**Meetings that have already happened, whose material is reachable, and which have no built",
        "vault.** This is the working list — pick from it rather than asking what is missing.",
        "",
        f"{len(queue)} entries, of which **{len(open_only)}** are fully open access.",
        "",
        "## Ready to build",
        "",
        "| Event | Ended | Topics | Access | Harvest | Endpoint | Vault |",
        "|---|---|---|---|---|---|---|",
    ]
    for s in queue:
        h = s.get("harvest") or {}
        ep = h.get("endpoint")
        ep_cell = f"[link]({ep})" if ep and str(ep).startswith("http") else "—"
        topics = ", ".join(s.get("topics", []))
        L.append(
            f"| **{s['name']}** | {date_range(s)} | {topics} "
            f"| {ACCESS_NOTE.get(s.get('access'),'—')} | {harvest_cell(s)} | {ep_cell} "
            f"| {vault_link(s)} |"
        )

    L += [
        "",
        "### Notes on individual entries",
        "",
    ]
    for s in queue:
        note = (s.get("harvest") or {}).get("notes")
        if note:
            L.append(f"- **{s['name']}** — {note}")

    if gated:
        L += [
            "",
            "## Concluded but not reachable",
            "",
            "Recorded so they are not repeatedly rediscovered as opportunities. These are gated,",
            "off-the-record, or have no harvestable artifact.",
            "",
            "| Event | Ended | Why |",
            "|---|---|---|",
        ]
        for s in sorted(gated, key=lambda s: as_date(s["end"]), reverse=True):
            why = (s.get("harvest") or {}).get("notes") or ACCESS_NOTE.get(
                s.get("access"), "—"
            )
            L.append(f"| {s['name']} | {date_range(s)} | {why} |")

    return "\n".join(L)


def page_by_topic(meta, sources, today) -> str:
    tax = meta["taxonomy"]
    L = [
        "# By topic",
        "",
        "Every source under each topic, crossing conferences, webinar series, journals, and news.",
        "Use this when the question is subject-shaped rather than calendar-shaped.",
        "",
        "Sources appear under each topic they carry, so entries repeat.",
        "",
    ]
    for topic, desc in tax.items():
        hits = [s for s in sources if topic in (s.get("topics") or [])]
        if not hits:
            continue
        anchor_events = [s for s in hits if is_event(s)]
        anchor_feeds = [s for s in hits if s["type"] in FEED_TYPES]
        L += [f"## {desc}", "", f"`{topic}` · {len(hits)} sources", ""]
        if anchor_events:
            L += ["| Event | When | Access | Vault |", "|---|---|---|---|"]
            for s in sorted(
                anchor_events,
                key=lambda s: (as_date(s.get("start")) or dt.date.max),
            ):
                L.append(
                    f"| {s['name']} | {date_range(s)} | {ACCESS_NOTE.get(s.get('access'),'—')} "
                    f"| {vault_link(s)} |"
                )
            L.append("")
        if anchor_feeds:
            names = ", ".join(sorted(s["name"] for s in anchor_feeds))
            L += [f"**Watchlist:** {names}", ""]
    return "\n".join(L)


def page_watchlist(sources) -> str:
    journals = [s for s in sources if s["type"] == "journal"]
    news = [s for s in sources if s["type"] == "news"]

    L = [
        "# Watchlist — journals and news",
        "",
        "**Kept deliberately separate from the vaults.**",
        "",
        "Conferences are bounded: a meeting happens, produces a fixed set of abstracts or papers, and is",
        "done. Journals and news never close. Folding them into the same structure would mean either",
        "curating an unbounded stream to vault standard — which does not scale — or dropping vault",
        "standards to feed volume. Curated vaults and an aggregator feed are different products, and",
        "mixing them dilutes both.",
        "",
        "So this page is an index of *where to look*, with the machine-readable endpoint recorded next to",
        "each entry. It is not a reading list and it is not summarized content.",
        "",
        "## Journals",
        "",
        "| Journal | Cadence | Topics | Access | Feed |",
        "|---|---|---|---|---|",
    ]
    for s in journals:
        ep = (s.get("harvest") or {}).get("endpoint")
        ep_cell = f"[{(s.get('harvest') or {}).get('method')}]({ep})" if ep else "—"
        L.append(
            f"| **{s['name']}** | {s.get('cadence','—')} | {', '.join(s.get('topics',[]))} "
            f"| {ACCESS_NOTE.get(s.get('access'),'—')} | {ep_cell} |"
        )

    L += [
        "",
        "## News and commentary",
        "",
        "| Source | Cadence | Topics | Access | Feed |",
        "|---|---|---|---|---|",
    ]
    for s in news:
        ep = (s.get("harvest") or {}).get("endpoint")
        ep_cell = f"[{(s.get('harvest') or {}).get('method')}]({ep})" if ep else "—"
        L.append(
            f"| **{s['name']}** | {s.get('cadence','—')} | {', '.join(s.get('topics',[]))} "
            f"| {ACCESS_NOTE.get(s.get('access'),'—')} | {ep_cell} |"
        )

    notes = [s for s in journals + news if (s.get("harvest") or {}).get("notes")]
    if notes:
        L += ["", "## Notes", ""]
        for s in notes:
            L.append(f"- **{s['name']}** — {s['harvest']['notes']}")

    L += [
        "",
        "## A caution about volume",
        "",
        "The bioRxiv feed alone will outproduce every conference in this corpus combined, and most of it",
        "will be irrelevant. Filter hard before anything from this page earns a place in a vault. The",
        "highest-signal entry here is probably the ACIR Weekly Digest — curated by domain experts, low",
        "volume, immunotherapy-specific.",
    ]
    return "\n".join(L)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--today", help="override today's date (YYYY-MM-DD)")
    ap.add_argument("--check", action="store_true", help="fail if pages are stale")
    args = ap.parse_args()

    today = dt.date.fromisoformat(args.today) if args.today else dt.date.today()
    meta, sources = load()

    ids = [s["id"] for s in sources]
    if len(ids) != len(set(ids)):
        dupes = {i for i in ids if ids.count(i) > 1}
        sys.exit(f"duplicate ids in registry: {sorted(dupes)}")

    stale: list = []
    write(OUT_DIR / "index.md", page_index(meta, sources, today), args.check, stale)
    write(OUT_DIR / "radar.md", page_radar(sources, today), args.check, stale)
    write(OUT_DIR / "harvest-queue.md", page_harvest_queue(sources, today), args.check, stale)
    write(OUT_DIR / "by-topic.md", page_by_topic(meta, sources, today), args.check, stale)
    write(OUT_DIR / "watchlist.md", page_watchlist(sources), args.check, stale)

    if args.check:
        if stale:
            sys.exit("stale registry pages: " + ", ".join(str(p) for p in stale))
        print("registry pages are up to date")
    else:
        print(f"wrote 5 registry pages for {today.isoformat()} from {len(sources)} sources")


if __name__ == "__main__":
    main()
